version: '3.3'
services:
  seleniumhub:
    build: selenium
    ports:
      - "4444:4444"
  db:
    image: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis
  web:
    build: .
    command: bash -c "rm -rf celeryd.pid && celery -A app.celery worker -l INFO --detach && flask run --host=0.0.0.0"
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=./app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    depends_on:
      - db
      - redis
      - seleniumhub

