version: '3.3'
services:
  selenium-hub:
    image: selenium/hub:3.12.0-cobalt
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14.0-arsenic
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  db:
    image: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis

  worker:
    build:
      context: celery-app
    depends_on:
      - redis
  web:
    build:
      context: ./web
    command: python app.py
    ports:
      - "5000:5000"
    links:
      - selenium-hub
    environment:
    - HUB_HOST=selenium-hub
    - HUB_PORT=4444
    depends_on:
    - db
    - selenium-hub
    - firefox
    - redis
    - worker

