version: '3.3'
services:
  seleniumhub:
    build: selenium
    environment:
      - PORT=4444
    ports:
      - "4444:4444"
  db:
    image: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis
  worker:
    build: .
    command: celery -A app.celery worker
    volumes:
      - .:/code
    environment:
      - FLASK_APP=./app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    depends_on:
      - redis
  web:
    build: .
    command: start price_miner
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=./app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    depends_on:
      - db
      - redis
      - seleniumhub

